// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package testpb is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	MyMsg
*/
package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyMsg struct {
	Age   int32  `protobuf:"varint,1,opt,name=Age" json:"Age,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *MyMsg) Reset()                    { *m = MyMsg{} }
func (m *MyMsg) String() string            { return proto.CompactTextString(m) }
func (*MyMsg) ProtoMessage()               {}
func (*MyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MyMsg) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *MyMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyMsg) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*MyMsg)(nil), "testpb.myMsg")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0x94, 0x9c, 0xb9, 0x58,
	0x73, 0x2b, 0x7d, 0x8b, 0xd3, 0x85, 0x04, 0xb8, 0x98, 0x1d, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x83, 0x40, 0x4c, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0x20, 0x23, 0x3f, 0x2f, 0x55, 0x82,
	0x19, 0x2c, 0x08, 0xe1, 0x24, 0xb1, 0x81, 0xcd, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x85,
	0xae, 0xbe, 0x32, 0x61, 0x00, 0x00, 0x00,
}
